### ISSUE TITLE
Error transforming 'typescript'

### ISSUE THREAD

**Issue by jamesopstad** [sveltejs/svelte-preprocess#150]
**Describe the bug**
Svelte-preprocess is throwing an error when I try to process typescript.

**Logs**
```
(node:10581) UnhandledPromiseRejectionWarning: Error: [svelte-preprocess] Error transforming 'typescript'.

Message:
The "path" argument must be of type string. Received undefined
```

**To Reproduce**
```javascript
const svelte = require('svelte/compiler')
const sveltePreprocess = require('svelte-preprocess')

const test = `
  <script lang="typescript">
    const val: string = 'Hello World';
  </script>
`

async function compile() {
  const processed = await svelte.preprocess(test, sveltePreprocess())
  console.log(processed)
}

compile()
```

**Expected behavior**
That the typescript will be processed and a new string logged to the console.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.dirname (path.js:1128:5)
    at Object.transformer [as typescript] (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/transformers/typescript.js:1:3172)
    at Object.exports.runTransformer (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/utils.js:1:2504)
    at async /Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/autoProcess.js:1:1182
    at async script (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/autoProcess.js:1:2137)
    at async /Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26746:32
    at async Promise.all (index 0)
    at async replace_async (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26716:52)
    at async Object.preprocess (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26741:19)
    at throwError (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/utils.js:1:629)
    at Object.exports.runTransformer (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/utils.js:1:2579)
    at async /Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/autoProcess.js:1:1182
    at async script (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte-preprocess/dist/autoProcess.js:1:2137)
    at async /Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26746:32
    at async Promise.all (index 0)
    at async replace_async (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26716:52)
    at async Object.preprocess (/Users/jamesopstad/Desktop/preprocess-example/node_modules/svelte/compiler.js:26741:19)
    at async compile (/Users/jamesopstad/Desktop/preprocess-example/preprocess-example.js:11:21)

</details>

**Information about your project:**

Node v14.2.0
svelte-preprocess v3.7.4

**Comment by jamesopstad** [comment]
It seems adding the optional `filename` argument to `svelte.preprocess` resolves this. Is this required then? It would be useful to know what it's used for.

**Comment by kaisermann** [comment]
Hey @jamesopstad 👋 . The `filename` is essential for resolving the path of the current file in question and possible relative imports from it. The `filename` option is always set by the `svelte-loader` (https://github.com/sveltejs/svelte-loader/blob/master/index.js#L138) or `rollup-plugin-svelte` (https://github.com/sveltejs/rollup-plugin-svelte/blob/master/index.js#L227)
