### ISSUE TITLE
Cannot import typescript interface

### ISSUE THREAD

**Issue by kierangilliam** [sveltejs/svelte-preprocess#197]
**Describe the bug**
Beginning today, I have not been able to import interfaces into Svelte components. This same code worked yesterday.

**Logs**
```
[!] Error: 'Task' is not exported by src/types/index.ts, imported by src/pages/tasks/_task/TaskGroup.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/pages/tasks/_task/TaskGroup.svelte (1:27)
1: <script lang='ts'>
                     ^
2:     import { Task } from '@types'
3:     // Also does not work
Error: 'Task' is not exported by src/types/index.ts, imported by src/pages/tasks/_task/TaskGroup.svelte
```

**Repo**
[Found here](https://github.com/kierangilliam/svelte-preprocess-error)

**Expected behavior**
The ability to import interface `Task`.

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>
bundles src/main.js → dist/build/bundle.js...
[!] Error: 'Task' is not exported by src/types/index.ts, imported by src/pages/tasks/_task/TaskGroup.svelte
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/pages/tasks/_task/TaskGroup.svelte (1:27)
1: <script lang='ts'>
                     ^
2:     import { Task } from '@types'
3:     // Also does not work
Error: 'Task' is not exported by src/types/index.ts, imported by src/pages/tasks/_task/TaskGroup.svelte
    at error (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:5171:30)
    at Module.error (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:9603:16)
    at handleMissingExport (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:9525:28)
    at Module.traceVariable (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:9986:24)
    at ModuleScope.findVariable (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:8549:39)
    at FunctionScope.findVariable (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:2795:38)
    at ChildScope.findVariable (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:2795:38)
    at ReturnValueScope.findVariable (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:2795:38)
    at Identifier$1.bind (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:4152:40)
    at Property$1.bind (/Users/kierangill/Documents/git/cannot-import-delete-me/node_modules/rollup/dist/shared/rollup.js:2880:23)

</details>

**Information about the project:**

- Browser version: N/A
- OS: OS X 10.15.2
- `svelte-preprocess` version: 4.0.6
- Using Rollup

**Additional context**
Tried using both yarn and npm. Tried node versions 12.18.2 and 14.4.0.

**Comment by dummdidumm** [comment]
Importing interfaces this way is no longer supported. From the docs https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#typescript : "As we're only transpiling, it's not possible to import types or interfaces into your svelte component without using the new TS 3.8 type import modifier: import type { SomeInterface } from './MyModule' otherwise bundlers will complain that the name is not exported by MyModule."
