### ISSUE TITLE
ParseError: Unexpected Token after npm run build

### ISSUE THREAD

**Issue by Tommertom** [sveltejs/svelte-preprocess#234]
**Describe the bug**
npm run build fails after implementing Typescript support. I Googled and thought it is linked to a similar bug found earlier in https://github.com/UnwrittenFun/svelte-vscode/issues/86

But this solution (at the end, configuring svelte.config.js) does not work.

Repo: https://github.com/Tommertom/svelte-ionic-app/tree/Typescript

**Logs**
```
> svelte-app@1.0.0 build C:\Gebruikers\Developer\Src\svelte-ionic-app
> rollup -c


src/main.js → public/bundle...
[!] (plugin svelte) ParseError: Unexpected token
src\App.svelte
22:
23: function add_css() {
24:   var style = element("style");
      ^
25:   style.id = "svelte-ykqo9k-style";
26:   style.textContent = "html{--ion-font-family:\"Helvetica Neue\", \"Roboto\", sans-serif}";
ParseError: Unexpected token
    at error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\utils\error.ts:25:16)
```
**To Reproduce**
If you will, clone the branch "Typescript" and run `npm run build` or `npm run dev`.

**Expected behavior**
No error

**Stacktraces**

**Information about your project:**
Rollup, latest Chrome, Windows10
`svelte-preprocess` version 4.2.0

**Comment by kaisermann** [comment]
Hey @Tommertom 👋 

Are you able to reproduce the issue without `svelte-preprocess`?

**Comment by Tommertom** [comment]
Hi @kaisermann 

Valid point. Commenting out the preprocess config in rollup.config.js does not affect the error (it remains). Uncommenting `typescript` removes the error

(with no `script lang="ts"` references, so nothing to handle).


So not related to this package, right? I should close? 

Any suggestions how to look further?

**Comment by Tommertom** [comment]
Hi

new insights here:\

I updated @rolluo/plugin-typescript, and added tslib as dependency of typescript (not done automatically).

Now, if I add only the preprocess step I get the error Unexpected token:
````
> svelte-app@1.0.0 build C:\Gebruikers\Developer\Src\svelte-ionic-app
> rollup -c

loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module '@rollup/plugin-typescript' but never used

src/main.js → public/bundle...
[!] (plugin svelte) ParseError: Unexpected token
src\App.svelte
22:
23: function add_css() {
24:   var style = element("style");
      ^
25:   style.id = "svelte-ykqo9k-style";
26:   style.textContent = "html{--ion-font-family:\"Helvetica Neue\", \"Roboto\", sans-serif}";
ParseError: Unexpected token
    at error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\index.ts:93:3)
    at Parser$1.acorn_error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\index.ts:86:8)
    at read_expression (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\read\expression.ts:36:10)
    at mustache (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\state\mustache.ts:388:22)
    at new Parser$1 (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\index.ts:45:12)
    at parse (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\parse\index.ts:208:17)
    at compile (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\svelte\src\compiler\compile\index.ts:79:14)
    at C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup-plugin-svelte\index.js:252:22

```


If I only add the typescript step I get the error:
````

C:\Gebruikers\Developer\Src\svelte-ionic-app>npm run build

> svelte-app@1.0.0 build C:\Gebruikers\Developer\Src\svelte-ionic-app
> rollup -c

loaded rollup.config.js with warnings
(!) Unused external imports
default imported from external module 'svelte-preprocess' but never used

src/main.js → public/bundle...
[!] Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
node_modules\@grpc\grpc-js\package.json (2:9)
1: {
2:   "_args": [
            ^
3:     [
4:       "@grpc/grpc-js@1.1.1",
Error: Unexpected token (Note that you need @rollup/plugin-json to import JSON files)
    at error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:5171:30)
    at Module.error (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:9603:16)
    at tryParse (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:9517:23)
    at Module.setSource (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:9901:30)
    at ModuleLoader.addModuleSource (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:17776:20)
    at ModuleLoader.fetchModule (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:17830:9)
    at async Promise.all (index 13)
    at ModuleLoader.fetchStaticDependencies (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:17854:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (C:\Gebruikers\Developer\Src\svelte-ionic-app\node_modules\rollup\dist\shared\rollup.js:17831:9)

```

If I exclude both, I get no error.

Something wrong in my code, or???

**Comment by Tommertom** [comment]
Closing. I rebuilt the project from the Typescript starter. Now the error is gone.
