### ISSUE TITLE
Arrow Function not working on pug

### ISSUE THREAD

**Issue by clarenceeda** [sveltejs/svelte-preprocess#271]
**Describe the bug**
Arrow function not working on inline script

**Logs**
`
[!] (plugin svelte) ParseError: Unexpected token
src\pages\auth\login.svelte
32:     }
33: </script>
34: <Page loginScreen><LoginScreenTitle>Welcome</LoginScreenTitle><Block><List form onSubmit="{()=&gt;{e.preventDefault;handlesubmit}}"><ListInput label="Username" type="text" clearButton required onInput="{ function(e){ data.username = e.target.value} }"></ListInput><ListInput label="Password" type="password" 
required onInput="{ function(e){ data.password = e.target.value} }"></ListInput><p><Button fill round type="submit">Login</Button></p><p><Button round outline>Register</Button></p></List></Block></Page>
                                                                                                ^
ParseError: Unexpected token
    at error (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\index.ts:100:3)
    at Parser$1.acorn_error (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\index.ts:93:8)
    at read_expression (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\read\expression.ts:36:10)
    at read_sequence (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\state\tag.ts:499:23)
    at read_attribute_value (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\state\tag.ts:464:16)
    at read_attribute (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\state\tag.ts:372:11)
    at tag (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\state\tag.ts:173:22)
    at new Parser$1 (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\index.ts:52:12)
    at parse$3 (F:\root\merkado-store-f7\node_modules\svelte\src\compiler\parse\index.ts:215:17)
`

**Expected behavior**
This on happens only when using inline arrow function.
`
_=>{} === _=&gt;{}
`

![pre-process](https://user-images.githubusercontent.com/42695235/96668120-0e875a00-138d-11eb-93b8-8675a2258ce7.PNG)

Windows 10
"svelte-preprocess": "^4.5.1"
Rollup

**Comment by kaisermann** [comment]
Hey @clarenceeda 👋 

If you read the error closely, you'll see that `pug` is transforming your `=>` into it HTML entity value: `&gt;`. You can fix this by using `onInput!={}` instead of `onInput={}`. Here it is in the docs: https://github.com/sveltejs/svelte-preprocess/blob/master/docs/preprocessing.md#pug

**Comment by MS-ELEX** [comment]
Me too!!!
Same problem.

![1](https://user-images.githubusercontent.com/16563756/103645159-e5916100-4f9a-11eb-8436-99263e4676d8.png)
![2](https://user-images.githubusercontent.com/16563756/103645336-2be6c000-4f9b-11eb-8f64-d3960f8d3853.png)

preprocesser (pug)  "{() => function_name()}"   convert  "{()=&gt; function_name()}"

**Comment by kaisermann** [comment]
@MS-ELEX Please read the answer that closed this issue.
