### ISSUE TITLE
using @use rules inside `:global { ... }` throws an error

### ISSUE THREAD

**Issue by YogliB** [sveltejs/svelte-preprocess#314]
**Describe the bug**
I'm trying to use svelte-preprocess to import external `sass` files with `@use`.
If I try to put the rule inside a `:global { ... }` rule I get an error.

**Logs**
```bash
PS D:\Projects\svelte-examples\examples\external-scss> pnpm dev

> svelte-app@1.0.0 dev D:\Projects\svelte-examples\examples\external-scss
> rollup -c -w

rollup v2.39.0
bundles src/main.js → public\build\bundle.js...
[!] (plugin svelte) Error: This at-rule is not allowed here.
  ╷
3 │     @use "@material/button/styles";
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\components\Button.svelte 3:5  root stylesheet
src\components\Button.svelte
Error: This at-rule is not allowed here.
  ╷
3 │     @use "@material/button/styles";
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src\components\Button.svelte 3:5  root stylesheet
    at Object._newRenderError (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:13531:19)
    at Object._wrapException (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:13374:16)
    at _render_closure1.call$2 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:80362:21)
    at _RootZone.runBinary$3$3 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:27258:18)
    at _FutureListener.handleError$1 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:25786:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:26083:49)
    at Object._Future__propagateToListeners (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:4543:77)
    at _Future._completeError$2 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:25916:9)
    at _AsyncAwaitCompleter.completeError$2 (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:25259:12)
    at Object._asyncRethrow (D:\Projects\svelte-examples\node_modules\.pnpm\sass@1.32.7\node_modules\sass\sass.dart.js:4292:17)
```
**To Reproduce**
[live repo](https://github.com/YogliB/svelte-examples/tree/master/examples/external-scss)

**Expected behavior**
No errors, and the `@use` rule is scoped globally.

**Information about your project:**

- Windows 10

- pnpm

- `svelte-preprocess` version 4.6.8

- Rollup

**Comment by kaisermann** [comment]
Hey, @YogliB 👋 that's happening because putting a `@use` rule inside a `:global {}` rule is not a valid in `sass`. The global attribute/selector preprocessor os executed after scss transforms your content, so it needs to be able to parse a valid scss code. You can try using the global attribute.

```svelte
<style lang="scss" global>
  ...
</style>
```

**Comment by YogliB** [comment]
good to know 😊

that was my plan B, since it make me use extra CSS classes to get my styles to scope...
