### ISSUE TITLE
Error when trying to build svelte app after v4.6.8 version

### ISSUE THREAD

**Issue by santiagogdo** [sveltejs/svelte-preprocess#315]
**Describe the bug**
I noticed a possible bug when trying to build a svelte app. It happens when using the last `svelte-preprocess` version (v.4.6.8). If I downgrade the version to v.4.6.7, the issue doesn't occur.

**To Reproduce**
Clone the svelte template, run the script to setup Typescript and build the project.

**Expected behavior**
The svelte app build should be successful.

**Stacktraces**

<details>
  <summary>Stack trace</summary>

`[!] TypeError: Cannot destructure property 'access' of 'undefined' or 'null'.
TypeError: Cannot destructure property 'access' of 'undefined' or 'null'.
    at Object.<anonymous> (C:\Users\myUser\Desktop\test\node_modules\svelte-preprocess\dist\modules\tagInfo.js:27:35)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\myUser\Desktop\test\node_modules\rollup\dist\shared\loadConfigFile.js:516:13)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\myUser\Desktop\test\node_modules\svelte-preprocess\dist\autoProcess.js:24:19)
`

</details>

**Additional context**
I noticed that between the v.4.6.8 and v.4.6.7, in [this commit](https://github.com/sveltejs/svelte-preprocess/commit/e742da9fb968e12f1515f7fa04962b90c4648627), the way `fs.access` is imported changed. Perhaps the issue could be related to this?

**Comment by HEmile** [comment]
I am getting the same crash. It seems to be related to fs.promises.

**Comment by kaisermann** [comment]
Hey, @santiagogdo 👋  I'm going to roll back this soon. What's your node version?

**Comment by kaisermann** [comment]
Should be fixed in v4.6.9 🎉

**Comment by santiagogdo** [comment]
> Hey, @santiagogdo 👋 What's your node version?
> 
> Reverted it in v4.6.9 🎉

I'm using node v11.9.0. It is working now, thanks for the quick help!
