### ISSUE TITLE
ts.findConfigFile can return undefined and break transform

### ISSUE THREAD

**Issue by rdmurphy** [sveltejs/svelte-preprocess#341]
**Describe the bug**
I've started seeing an error with `svelte-preprocess` that I've chased down to `ts.findConfigFile` returning `undefined`, which makes the following `isAbsolute` call fail. Not quite sure what the answer is though. 😬 Or if that's a recent change to TypeScript.

https://github.com/sveltejs/svelte-preprocess/blob/bf4777645578833edd3a6b592fb746f2248e8b90/src/transformers/typescript.ts#L70-L76

**Logs**
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.isAbsolute (path.js:1029:5)
    at loadTsconfig (/Project/svelte-preprocess/dist/transformers/typescript.js:50:27)
    at transformer (/Project/svelte-preprocess/dist/transformers/typescript.js:77:11)
    at script (/Project/svelte-preprocess/dist/processors/typescript.js:34:35)
    at async process_single_tag (/Project/svelte/compiler.js:30178:28)
    at async Promise.all (index 0)
    at async replace_in_code (/Project/svelte/compiler.js:30071:27)
    at async process_tag (/Project/svelte/compiler.js:30191:30)
    at async preprocess (/Project/svelte/compiler.js:30229:31)
```

**Expected behavior**
Should work as expected.

**Information about your project:**

- Your operating system: MacOS 11.2.3

- Node.js version v14.16.1

- `svelte-preprocess` version 4.7.0

- Using Rollup + `rollup-plugin-svelte`

**Comment by rdmurphy** [comment]
Poked on this a little further and I'm pretty sure this was introduced in `4.7.0` with https://github.com/sveltejs/svelte-preprocess/pull/328. Rolling back to `4.6.9` fixed it. I think it's no longer accounting for the scenario where no `tsconfig.json` exists?

**Comment by kaisermann** [comment]
Hey, @rdmurphy 👋  Will close this in favour of #339.
