### ISSUE TITLE
ParseError when added to blank Svelte template

### ISSUE THREAD

**Issue by sswatson** [sveltejs/svelte-preprocess#343]
I set up a blank Svelte template and added svelte-preprocessor to it, and that gives me a `ParseError`. I'm really not sure if it's an issue with svelte-preprocess or the template, but I'm hoping someone can point me in the right direction.

**To Reproduce**

1. Set up the basic Svelte template per the instructions on the svelte.dev landing page (`npx degit sveltejs/template svelte-tmp`).
2. Add preprocessing with sass and postcss: `npm i -D svelte-preprocess sass postcss` (per the instructions for the _attractions_ UI components).
3. Add `import sveltePreprocess from 'svelte-preprocess'` to the rollup config file, as well as adding `svelte({preprocessor: sveltePreprocess()})` as the first element of the array of plugins.

When I do this, rollup hangs. The stack trace:

<details>
  <summary>Stack trace</summary>
bundles src/main.js → public/build/bundle.js...
[!] (plugin svelte) ParseError: The keyword 'let' is reserved
src/App.svelte
22: 
23: function create_default_slot(ctx) {
24:   let t;
      ^
25: 
26:   return {
ParseError: The keyword 'let' is reserved
    at error (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/utils/error.ts:25:16)
    at Parser$1.error (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/index.ts:100:3)
    at Parser$1.acorn_error (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/index.ts:93:8)
    at read_expression (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/read/expression.ts:36:10)
    at mustache (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/state/mustache.ts:392:22)
    at new Parser$1 (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/index.ts:52:12)
    at parse (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/parse/index.ts:216:17)
    at compile (/Users/sswatson/Desktop/svelte-tmp/node_modules/svelte/src/compiler/compile/index.ts:91:14)
    at Object.transform (/Users/sswatson/Desktop/svelte-tmp/node_modules/rollup-plugin-svelte/index.js:111:21)
    at /Users/sswatson/Desktop/svelte-tmp/node_modules/rollup/dist/shared/rollup.js:18870:25
</details>

**Information about your project:**

I'm using Chrome on macOS Catalina with svelte-preprocess version 4.7.0 and rollup version 2.3.4.

**Comment by kaisermann** [comment]
Hey, @sswatson 👋 Would you be able to share a repro? This doesn't seem related to `svelte-preprocess` and I couldn't reproduce it from my side.

**Comment by sswatson** [comment]
That's helpful information. [Here's](https://github.com/sswatson/svelte-preprocess-error-repro) a repo which reproduces the error.

**Comment by kaisermann** [comment]
There are two calls for the rollup svelte plugin and `preprocessor` is not a valid option, it should be `preprocess`. Change to this and things should be good:
![image](https://user-images.githubusercontent.com/12702016/118058553-d1a0a600-b364-11eb-9446-8b887cd3a58d.png)
