### ISSUE TITLE
Can't get PUG mixins to work

### ISSUE THREAD

**Issue by geoidesic** [sveltejs/svelte-preprocess#369]
**Describe the bug**
Pug mixins have been provided to support conditional statements in Svelte... but they don't seem to work.

Following the docs here:
https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#pug

I tried this:
```
div
  +if(showDialog)
    Dialog(
      title="Are you sure you want to exit?"
      closeCallback="{close}"
      danger
    )
```

**Logs**
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
localhost/:1 GET http://localhost:3000/ 500 (Internal Server Error)
client.ts:13 [vite] connecting...
client.ts:43 [vite] connected.
index.mjs?v=5d6fee82:1667 <Error> received an unexpected slot "default".
validate_slots @ index.mjs?v=5d6fee82:1667
instance @ error.svelte? [sm]:5
init @ index.mjs?v=5d6fee82:1485
Error @ error.svelte? [sm]:15
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:241
Proxy<Error> @ proxy.js:341
create_if_block_2 @ root.svelte? [sm]:39
create_default_slot @ root.svelte? [sm]:38
create_slot @ index.mjs?v=5d6fee82:61
create_fragment @ __layout.svelte? [sm]:2
init @ index.mjs?v=5d6fee82:1500
_layout @ __layout.svelte? [sm]:2
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:241
Proxy<__layout> @ proxy.js:341
create_fragment @ root.svelte? [sm]:37
init @ index.mjs?v=5d6fee82:1500
Root @ root.svelte? [sm]:17
createProxiedComponent @ svelte-hooks.js:245
ProxyComponent @ proxy.js:241
Proxy<Root> @ proxy.js:341
_init @ start.js:646
start @ start.js:530
async function (async)
start @ start.js:483
start @ start.js:1096
(anonymous) @ (index):227
content_script.js:75 Rivet content_script initialised

**To Reproduce**
I just installed `svelte-preprocessor` and used `https://github.com/Leftium/pug-adder` to set up the config.

**Expected behavior**
I expect the `if` statement to compile

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

Unexpected token
ParseError: Unexpected token
    at error (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16752:20)
    at Parser$1.error (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16828:10)
    at Parser$1.acorn_error (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16822:15)
    at read_expression (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:7460:17)
    at mustache (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16503:29)
    at new Parser$1 (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16787:22)
    at parse$3 (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:16919:21)
    at compile (/Users/repo/GitHub/peakVTT/node_modules/svelte/compiler.js:30012:18)
    at compileSvelte (/Users/repo/GitHub/peakVTT/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:244:48)
    at async TransformContext.transform (/Users/repo/GitHub/peakVTT/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:837:27)

</details>

**Information about your project:**

- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)

- `svelte-preprocess` version (Please check you can reproduce the issue with the latest release!)

- Whether your project uses Webpack or Rollup

**Comment by geoidesic** [comment]
Aargh.. never mind. I had left out the single-quotes:
```
div
  +if('showDialog')
    Dialog(
      title="Are you sure you want to exit?"
      closeCallback="{close}"
      danger
    )
```
