### ISSUE TITLE
stylus: Compound class global selector inside at-rules doesn't compile

### ISSUE THREAD

**Issue by ZerdoX-x** [sveltejs/svelte-preprocess#376]
**Describe the bug**
Strange bug where `ul :global(.text)` selector inside at-rules doesn't compile: `expected ")", got "."`

**Logs**
```
[!] (plugin svelte) ParseError: src/App.svelte:3:15
   1| 
   2| @supports (display: grid) {
   3|   ul :global(.text) {
--------------------^
   4|     background-color: tomato;
   5|   }
   6| }

expected ")", got "."

src/App.svelte
ParseError: src/App.svelte:3:15
   1| 
   2| @supports (display: grid) {
   3|   ul :global(.text) {
--------------------^
   4|     background-color: tomato;
   5|   }
   6| }

expected ")", got "."
```

**To Reproduce**
[ZerdoX-x/svelte-preprocess_bug-reproduced](https://github.com/ZerdoX-x/svelte-preprocess_bug-reproduced)

**Stacktraces**
<details>
  <summary>Stack trace</summary>

  ```
    at Parser.error (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:259:11)
    at Parser.expect (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:287:12)
    at Parser.functionCall (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:1810:10)
    at Parser.primary (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2291:18)
    at Parser.member (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2174:21)
    at Parser.subscript (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2152:21)
    at Parser.unary (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2143:17)
    at Parser.defined (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2115:21)
    at Parser.multiplicative (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2089:21)
    at Parser.additive (/home/zerdox/tmp/template/node_modules/stylus/lib/parser.js:2074:21)
  ```

</details>

**Information about your project:**
- Your operating system: 5.12.10-arch1-1
- `svelte-preprocess` version: ^4.7.3
- Issue can be reproduced with both rollup and vite (n/a info about webpack)

**Additional context**
Workaround:
Use `[class~="some-class-name"]` instead of `.some-class-name`

**Comment by kaisermann** [comment]
Hey, @ZerdoX-x 👋  Thanks for providing the logs and repro! I was able to reproduce it even in the [online stylus compiler](https://beautifytools.com/stylus-compiler.php). It seems the Stylus parser doesn't know how to handle the `:global` pseudo-selector inside of an at-rule. I'm afraid I'm not sure what's the best fix for this. A very naive one would be to replace all occurrences of `:global` with something parseable like `#:global` (don't even know why this works) before sending to the stylus compiler and then rolling it back in the processed css.

**Comment by kaisermann** [comment]
A workaround would be to use nested at-rules:

https://stylus-lang.com/try.html#?code=ul%20%3Aglobal(.text)%20%7B%0A%20%20%20%20%40supports%20(display%3A%20grid)%20%7B%0A%20%20%20%20%20%20%20%20background-color%3A%20tomato%3B%0A%20%20%20%20%7D%0A%7D

**Comment by ZerdoX-x** [comment]
@kaisermann My workaround with attribute selector works fine for me. So I will create third issue (?) in stylus repo.. I guess it can't be resolved because :global thing can be appeared only in svelte and it's not really stylus problem..

**Comment by ZerdoX-x** [comment]
Migrated to stylus/stylus/issues/2594
