### ISSUE TITLE
From 4.9.0: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/svelte-preprocess#396]
Upgrading from `4.8.0` to `4.9.0` I get this:

```
12:45:35 PM [vite] Internal server error: Cannot read property 'split' of undefined
  Plugin: vite-plugin-svelte
  File: C:/kit/src/routes/__error.svelte
      at Object.parseAttributes (C:\kit\node_modules\svelte-preprocess\dist\modules\markup.js:19:10)
      at getScriptContent (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:47:38)
      at injectVarsToCode (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:83:20)
      at mixedImportsTranspiler (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:205:26)
      at transformer (C:\kit\node_modules\svelte-preprocess\dist\transformers\typescript.js:275:11)
      at Object.exports.transform (C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:37:12)
      at async C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:113:29
      at async script (C:\kit\node_modules\svelte-preprocess\dist\autoProcess.js:143:33)
      at async process_single_tag (file:///C:/kit/node_modules/svelte/compiler.mjs:31534:27)
      at async Promise.all (index 0)
Cannot read property 'split' of undefined
```

I'm using `SvelteKit@1.0.0-next.162`.

**Comment by kaisermann** [comment]
Hey, @frederikhors 👋 Fixed on 4.9.1, thanks for the report!

Out of curiosity, are you defining typescript as the default language?

**Comment by frederikhors** [comment]
> Out of curiosity, are you defining typescript as the default language?

Yes, I'm using SvelteKit with TS. Are you asking this?

**Comment by kaisermann** [comment]
Not exactly, sorry! I meant if you are using `typescript` without writing `lang="ts"` on your script tag 😅  Can you share the top of the script tag that caused the error? I'm trying to write a test for this issue.

**Comment by frederikhors** [comment]
Nope, I'm using `<script lang="ts">`.

Is there a way I can set it to default?

**Comment by dummdidumm** [comment]
No (you shouldn't). So what's the file content with which this error is reproducible?
