### ISSUE TITLE
get error "Cannot read properties of undefined (reading 'length')"  in sveltekit when use coffeescript

### ISSUE THREAD

**Issue by happy-little-one** [sveltejs/svelte-preprocess#413]
routes/index.svelte
```
<script lang="coffee">
text = 'hello'
</script>

<h1>{text}</h1>
```

svelte.config.js
```
import preprocess from 'svelte-preprocess'

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
  },
  preprocess: preprocess({ coffeescript: true }),
}
export default config
```

I really like coffee, hope this would be fixed faster, thanks.

**Comment by babichjacob** [comment]
Me too. Full stack trace:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Function.from_processed (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:24789:61)
    at processed_content_to_code (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31499:23)
    at processed_tag_to_code (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31513:26)
    at process_single_tag (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31554:16)
    at Function.all (<anonymous>:null:null)
    at replace_in_code (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31432:26)
    at process_tag (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31556:29)
    at preprocess (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/svelte@3.43.0/node_modules/svelte/compiler.mjs:31594:30)
    at compileSvelte (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.24_svelte@3.43.0+vite@2.5.10/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:302:20)
    at TransformContext.transform (file:///Users/jacob/Repositories/svelte-add/node_modules/.pnpm/@sveltejs+vite-plugin-svelte@1.0.0-next.24_svelte@3.43.0+vite@2.5.10/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1374:27)
    at Object.transform (/Users/jacob/Repositories/svelte-add/node_modules/.pnpm/vite@2.5.10/node_modules/vite/dist/node/chunks/dep-36bf480c.js:50373:30)
    at transformRequest (/Users/jacob/Repositories/svelte-add/node_modules/.pnpm/vite@2.5.10/node_modules/vite/dist/node/chunks/dep-36bf480c.js:65414:29)
    at instantiateModule (/Users/jacob/Repositories/svelte-add/node_modules/.pnpm/vite@2.5.10/node_modules/vite/dist/node/chunks/dep-36bf480c.js:75076:10)
```

This only happens in SvelteKit. Non-SvelteKit Vite projects have working CoffeeScript.


You can create a reproduction environment with
```js
npm init --yes @svelte-add/kit@latest repro-coffeescript -- --with coffeescript
```

and edit `src/routes/index.svelte` wherein you only have to add `lang="coffee"` on the script tag to get this error.

A more compelling sample of CoffeeScript to test with is here:
```html
<script lang="coffee">
	count = 0
	# Svelte $: reactive syntax is illegal in CoffeeScript.
        # The following trick sandwiches reactive CoffeeScript
	# between two bits of escaped JS that start/stop the
	# reactive block.
	`$: {`  ## Start Svelte reactive block.
	console.log {count}
	if count >= 10
		alert 'count is dangerously high!'
		count = 9
	`}`     ## End reactive block.
	# This statement is outside the reactive block,
	# so it will only be executed once.
	console.log "Hello CoffeeScript! No parentheses/semicolons needed!"
	handleClick = () ->
		count += 1
</script>
```
