### ISSUE TITLE
MJML Rendering, "Cannot use import statement outside a module" on change

### ISSUE THREAD

**Issue by andreasnuesslein** [sveltejs/svelte-preprocess#429]
**Describe the bug**
I tried a custom preprocessor for mjml (mjml.io). My `preprocess()` looks like to:
```js
preprocess({
      postcss: true,
      mjml({ content }) {
        const code = mjml2html(content, { minify: true }).html;
        return { code };
      },
    })
```

With my svelte-file having something along the lines of:
```xml
<template lang="mjml">
  <mjml>
    <mj-body>
      <mj-text>
        Hello World.
      </mj-text>
    </mj-body>
  </mjml>
</template>
```

It works just nicely after a reload of `npm run dev`. But, as soon as I change a line in my template, (e.g. `Hello Globe`), I receive an error.

**Logs**
The browser says:
```
500
Cannot use import statement outside a module
SyntaxError: Cannot use import statement outside a module
    at new AsyncFunction (<anonymous>)
    at instantiateModule (.../node_modules/vite/dist/node/chunks/dep-be032392.js:66503:28)
```

the server:
```
10:35:23 AM [vite-plugin-svelte] .../src/routes/emails/welcome.svelte:5:15 A11y: <html> element should have a lang attribute
10:35:23 AM [vite] Error when evaluating SSR module /src/routes/emails/welcome.svelte:
SyntaxError: Cannot use import statement outside a module
    at new AsyncFunction (<anonymous>)
    at instantiateModule (.../node_modules/vite/dist/node/chunks/dep-be032392.js:66503:28)
Cannot use import statement outside a module
SyntaxError: Cannot use import statement outside a module
    at new AsyncFunction (<anonymous>)
    at instantiateModule (.../node_modules/vite/dist/node/chunks/dep-be032392.js:66503:28)
```

**Expected behavior**
Refreshing my browser output correctly with "Hello Globe"

**Information about your project:**
- Ubuntu 21.10,
- node 14.18.1, npm 8.1.1
- rollup
- svelte-preprocess version 4.9.8

Any help would be highly appreciated :)

Cheers

**Comment by andreasnuesslein** [comment]
I went another way with this, so I'm gonna close it. (The issue itself is still there though)
