### ISSUE TITLE
Named export 'sass' not found

### ISSUE THREAD

**Issue by basaran** [sveltejs/svelte-preprocess#431]
**Describe the bug**
I'm trying to import and configure preprocessor manually.

**To Reproduce**

Repo:
https://github.com/basaran/prep-issue

```
pnpm install -D svelte-preprocess;
```

then import in `svelte.config.js`

```
import { sass } from "svelte-preprocess";
```

**Expected behavior**
I was able to import like this with a standard svelte project.

**Stacktraces**

If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

file:///home/michael/websites/prep/svelte.config.js:1
import { sass } from "svelte-preprocess";
         ^^^^
SyntaxError: Named export 'sass' not found. The requested module 'svelte-preprocess' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'svelte-preprocess';
const { sass } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async load_config (file:///home/michael/websites/prep/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.196_svelte@3.44.1/node_modules/@sveltejs/kit/dist/cli.js:697:17)
    at async get_config (file:///home/michael/websites/prep/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.196_svelte@3.44.1/node_modules/@sveltejs/kit/dist/cli.js:769:10)
    at async file:///home/michael/websites/prep/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.196_svelte@3.44.1/node_modules/@sveltejs/kit/dist/cli.js:831:18

</details>

**Information about your project:**

- node v16.10.0
- 4.9.8
- Rollup

**Comment by HeyITGuyFixIt** [comment]
I'm experiencing the same issue but with postcss

**Comment by compeek** [comment]
I'm experiencing the same in a SvelteKit project. I've found that using the default import (e.g. `import sveltePreprocess from 'svelte-preprocess';`) and then using `sass` (or whatever preprocessor you want) off of that (e.g. `sveltePreprocess.sass()`) works, but I don't like to have to do that since it's supposed to support ESM.

**Comment by felixsanz** [comment]
bump!

**Comment by mattpilott** [comment]
I've run into this today and tracking back through the code it seems as though
`import { scss } from 'svelte-preprocess'`
should work

**Comment by muratgozel** [comment]
hey, looks like this module only supports commonjs, remove `"type": "module"` from the `package.json` if you can.

**Comment by Aoshisen** [comment]
some issue happened to me

**Comment by basaran** [comment]
It seems vitePreprocess is becoming the norm these days. In the meantime, this is an option for destructuring assignment. Just not at the esm import.

```
import sveltePreprocess from 'svelte-preprocess';
const { sass } = sveltePreprocess;
```
