### ISSUE TITLE
Plugin cannot process a component containing <style> in string or even comment

### ISSUE THREAD

**Issue by samijaber** [sveltejs/svelte-preprocess#507]
**Describe the bug**

I was initially trying to build this component and ran into errors:

```svelte
<script>
$: injectedStyles = () => `//some logic here`

$: injectedStyleScript = () => {
  return `<style>${injectedStyles()}</style>`;
};
</script>
    
{@html injectedStyleScript()}
```

After some more testing, I realized that the mere presence of the `<style>` string within `<script>`, even if in a string (or a comment!!) causes the `vite-plugin-svelte` plugin to crash with the following error:

### Reproduction

```svelte
<script>
	// export const value = '<style>test</style>';
</script>

<div>test</div>
```

**Logs**
Please include browser console and server logs around the time this bug occurred.

```
Error while preprocessing {filePath}.svelte - {filePath}:1:1: Unknown word
CssSyntaxError: Error while preprocessing {filePath}.svelte - {filePath}.svelte:1:1: Unknown word
    at Input.error (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/input.js:148:16)
    at Parser.unknownWord (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/parser.js:540:22)
    at Parser.other (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/parser.js:164:12)
    at Parser.parse (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/parser.js:72:16)
    at parse (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/postcss/lib/processor.js:28:14)
    at transformer (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/svelte-preprocess/dist/transformers/globalStyle.js:56:72)
    at transform (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)
    at async style (/Users/samijaber/code/work/builder/examples/svelte/sveltekit/node_modules/svelte-preprocess/dist/autoProcess.js:191:33)
```

**To Reproduce**
To help us help you, if you've found a bug please consider the following:

- Please create a small repo that illustrates the problem: https://github.com/samijaber/svelte-processor-style-bug

**Expected behavior**
This should be valid Svelte code as it works fine in the Svelte REPL

**Information about your project:**

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 164.56 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.asdf/installs/nodejs/16.14.0/bin/node
    Yarn: 3.2.0 - ~/.asdf/installs/nodejs/16.14.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 100.1.37.116
    Chrome: 100.0.4896.127
    Firefox: 97.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.34
    @sveltejs/kit: next => 1.0.0-next.311
    svelte: ^3.46.0 => 3.47.0
```

**Comment by bluwy** [comment]
Similar to https://github.com/sveltejs/vite-plugin-svelte/issues/315, it's an issue in Svelte https://github.com/sveltejs/svelte/issues/5292
