### ISSUE TITLE
Build error parsing a TypeScript enum outside immediate tsconfig

### ISSUE THREAD

**Issue by jtlapp** [sveltejs/svelte-preprocess#510]
**Describe the bug**
I'm getting a build error when I try to import a TS file into a svelte file when the TS file is outside the the scope of the svelte file's tsconfig. More specifically, my source is set up as follows:

```
tsconfig.json
src/
    backend/
    frontend/
        tsconfig.json
        component.svelte
    shared/
        shared.ts
```

Rollup errors when a component tries to import `shared.ts` if this file has an enum. VSCode reports no error.

I'm actually sharing a decent amount of code via the `shared/` directory, and everything functioned just fine up until I put an enum in a shared file. The error occurs regardless of whether I export the enum.

**Logs**
```
$ yarn run dev
yarn run v1.22.10
$ tsc && rollup -c -w
rollup v2.70.2
bundles src/frontend/main.ts → public/build/bundle.js...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/shared/constants.ts (3:7)
1: export const SITE_NAME = 'Starter Site';
2: 
3: export enum Permission {
          ^
4:   Read,
5:   Write,
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/joe/repos/svelte-ts-spa-starter/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/Users/joe/repos/svelte-ts-spa-starter/node_modules/rollup/dist/shared/rollup.js:12521:16)
    at Module.tryParse (/Users/joe/repos/svelte-ts-spa-starter/node_modules/rollup/dist/shared/rollup.js:12897:25)
    at Module.setSource (/Users/joe/repos/svelte-ts-spa-starter/node_modules/rollup/dist/shared/rollup.js:12800:24)
    at ModuleLoader.addModuleSource (/Users/joe/repos/svelte-ts-spa-starter/node_modules/rollup/dist/shared/rollup.js:22264:20)
```

**To Reproduce**
1. Install [this barebones repo](https://github.com/jtlapp/svelte-ts-spa-starter) that uses the above file structure.
2. Run `yarn`.
3. Run `yarn run dev` to demonstrate that the repo functions fine, serving on `localhost:80`, and even pulls in the constant `SITE_NAME` via `src/shared/constants.ts`.
4. Add the following to `src/shared/constants.ts`:

```ts
export enum Permission {
  Read,
  Write,
  admin
}
```

5. The repo should automatically rebuild and show the above error.

**Expected behavior**
This should not error. VSCode with the Svelte extension is not reporting an error.

**Information about your project:**

- MacOS 10.15.5
- `svelte-preprocess` version 4.10.6 (a fresh install)
- rollup v2.70.2

**Comment by jtlapp** [comment]
Wait. I found another shared file that is successfully exporting an enum. Something else must be going on.

**Comment by jtlapp** [comment]
Curiously, if I only `import type`, it's happy parsing TypeScript. In my example repo, put this in `src/shared/constants.ts`:

```ts
export const SITE_NAME = 'Starter Site';

export type Foo = string;
```

And this in `App.svelte`:

```ts
  import type { Foo } from '../shared/constants';
  const x: Foo = 'foo';
  console.log(x);
```

**Comment by jtlapp** [comment]
Maybe this is a problem with `@rollup/plugin-typescript`?

**Comment by jtlapp** [comment]
And I solved the problem by adding the last line you see in this tsconfig:

```json
{
  "extends": "@tsconfig/svelte/tsconfig.json",
  "compilerOptions": {
    "stripInternal": true,
    "strict": true,
    "pretty": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
  },
  "include": ["../**/*.ts"]
}
```

I'm not sure why it sometimes parses outside TS and sometimes doesn't without this line.

Hope you enjoyed the show!
