### ISSUE TITLE
Should not process <script type="module">

### ISSUE THREAD

**Issue by shir0u** [sveltejs/svelte-preprocess#522]
**Describe the bug**
When trying to resolve a module manually via `<svelte:head>` it throws an error.
This works normally if it is added to `index.html` directly but not in a svelte component.

**Logs**
No logs, just errors.

**To Reproduce**
```svelte
<svelte:head>
  <script type="module" src="/entry/entry-test.ts"></script>
</svelte:head>
```

`entry-test.ts` can contain anything.

**Expected behavior**
Expected to not process type module, as it's a standard type in the browser.

**Stacktraces**
```shell
Error while preprocessing **/views/index.svelte - Cannot find module './transformers/module'
Require stack:
- **/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/autoProcess.js
- **/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at **/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/autoProcess.js:36:77
    at async transform (**/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/autoProcess.js:36:29)
    at async **/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/autoProcess.js:118:29
    at async script (**/node_modules/.pnpm/svelte-preprocess@4.10.6_qvmludyoi2pshs55nieazfklm4/node_modules/svelte-preprocess/dist/autoProcess.js:148:33)
    at async process_single_tag (file:///**/node_modules/.pnpm/svelte@3.48.0/node_modules/svelte/compiler.mjs:32497:27
```

**Information about your project:**
```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 37.89 GB / 64.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 98.0.2
    Safari: 15.5
  npmPackages:
    @sveltejs/vite-plugin-svelte: 1.0.0-next.47 => 1.0.0-next.47 
    svelte: ^3.48.0 => 3.48.0 
    vite: 2.9.9 => 2.9.9 
```

**Comment by shir0u** [comment]
Further digging I have found an option to ignore such types.

```js
// this works for anybody that is interested.
sveltePreprocess({preserve: ['module']});
```

More details here: https://github.com/sveltejs/svelte-preprocess/blob/main/docs/preprocessing.md#auto-preprocessing-options

closing now as it is resolved.
