### ISSUE TITLE
Shorthand {src} attribute on <script> tag causes Typescript error

### ISSUE THREAD

**Issue by oodavid** [sveltejs/svelte-preprocess#604]
### Describe the bug

Using `<script {src} />` causes a Typescript error.
The `string` type is interpreted as `string | null | undefined`.
To fix, we can use `<script src={src} />

<img width="700" alt="Screenshot 2023-06-26 at 09 13 24" src="https://github.com/sveltejs/svelte/assets/46879/f4f20016-b64b-4d4b-bfbe-2e3643373b07">

<img width="463" alt="Screenshot 2023-06-26 at 09 14 30" src="https://github.com/sveltejs/svelte/assets/46879/b5a780da-58cf-4d45-b8ad-6b8dccde6dcc">

### Reproduction

```
<script lang="ts">
	export let src: string;
</script>

<svelte:head>
	<!-- Typescript error -->
	<script {src} />
	<!-- No error -->	
	<script src={src} />
</svelte:head>
```

### Logs

```shell
Preprocessing failed
Error: src attribute must be string
    at getTagInfo (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte-preprocess/dist/modules/tagInfo.js:32:19)
    at /Users/david/Documents/flow-mobile/www/admin/node_modules/svelte-preprocess/dist/autoProcess.js:95:115
    at Object.script (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte-preprocess/dist/autoProcess.js:147:39)
    at wrappedPreprocessor.script (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte-check/dist/src/index.js:94474:47)
    at process_single_tag (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte/compiler.cjs:45875:27)
    at /Users/david/Documents/flow-mobile/www/admin/node_modules/svelte/compiler.cjs:45560:4
    at String.replace (<anonymous>)
    at calculate_replacements (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte/compiler.cjs:45558:9)
    at replace_in_code (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte/compiler.cjs:45599:29)
    at process_tag (/Users/david/Documents/flow-mobile/www/admin/node_modules/svelte/compiler.cjs:45892:32) {
  __source: 'Script'
}
/Users/david/Documents/flow-mobile/www/admin/src/components/script.svelte:1:19
Error: src attribute must be string (svelte(script))
```

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 393.44 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Edge: 114.0.1823.51
    Firefox: 113.0.2
    Safari: 16.3
  npmPackages:
    svelte: ^4.0.0 => 4.0.0
```

### Severity

annoyance

**Comment by oodavid** [comment]
I've noticed that I'm no longer seeing an issue here.

For reference, here's my package.json (lightly redacted), although I'm not sure when this issue disappeared.

```json
{
	"name": "admin2",
	"version": "0.0.1",
	"engines": {
		"node": ">=18.0.0"
	},
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"test": "playwright test",
		"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json --output human --compiler-warnings 'a11y-distracting-elements:ignore,a11y-click-events-have-key-events:ignore,a11y-no-static-element-interactions:ignore,a11y-no-noninteractive-tabindex:ignore,a11y-autofocus:ignore'",
		"check:watch": "npm run check -- --watch",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@playwright/test": "^1.42.1",
		"@sveltejs/adapter-static": "^3.0.1",
		"@sveltejs/kit": "^2.5.5",
		"@sveltejs/vite-plugin-svelte": "^3.0.2",
		"@typescript-eslint/eslint-plugin": "^7.1.1",
		"@typescript-eslint/parser": "^7.1.1",
		"eslint": "^8.57.0",
		"eslint-config-prettier": "^9.1.0",
		"prettier": "^3.2.5",
		"prettier-plugin-svelte": "^3.2.2",
		"sass": "^1.72.0",
		"svelte": "^4.2.12",
		"svelte-check": "^3.6.8",
		"tslib": "^2.6.2",
		"typescript": "^5.4.3",
		"vite": "^5.2.7",
		"eslint-plugin-svelte": "^2.35.1"
	},
	"type": "module"
}
```
